### ISSUE TITLE
Reverting 'inject into file' should not attempt to change files that do not exist

### ISSUE THREAD

**Issue by zwippie** [rails/thor#463]
For example, if `append_to_file 'model/thing.rb', 'content'` is _revoked_ but the file does not exist anymore, the command will fail with an exception that ends like this:

```
/home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /home/zwippie/src/testing/app/models/thing.rb (Errno::ENOENT)
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:73:in `revoke!'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:92:in `action'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
    from /home/zwippie/src/trailblazer/lib/generators/rails/trailblazer_controller_generator.rb:20:in `add_crud_dependency_to_model'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/zwippie/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
```

In this case, the error is triggered by a Rails generator that adds a line to a generated model. It was called with `rails d scaffold Thing -c trailblazer_controller`, just to give some context.

If I am not mistaking, there is no check in (or near) `InjectIntoFile#revoke!` to see if the file in question exists. I can find no clues in the specs or docs that this should happen, so perhaps this is the required behaviour. It can be easily fixed though.

This might be attributed to my misunderstanding of Thor or the context of my case (Rails generators). I'm willing to make the neccesary changes and PR if this should be fixed.

**Comment by vcavallo** [comment]
I had the same problem today, @zwippie. I believe my #505 addresses it.

**Comment by anyelopetit** [comment]
I fixed that problem before I call `append_to_file`:
```
  directory = "#{Rails.root}/some/path/#{file_name}"
    if File.directory?(directory)
      append_to_file 'Gemfile' do
        "gem '#{file_name}', path: 'rockets/#{file_name}'\n"
      end
      say "=== #{class_name}'s gem added to Gemfile ===\n", :green
      true
    else
      say "!!! Cannot add #{class_name} gem to Gemfile. Directory doesn't exist !!!\n", :red
      false
    end
  end
```
