### ISSUE TITLE
undefined method say

### ISSUE THREAD

**Issue by Ogromny** [rails/thor#526]
Hi i have a problem

``` ruby
require 'thor'

class Duck < Thor

    def self.duck
        say("duck?")
    end

end

Duck.duck
```

`````` sh
duckduck.rb:6:in `duck': undefined method `say' for Duck:Class (NoMethodError) 
from duckduck.rb:11:in `<main>'```


I'm French and i have a very poor english sorry :/
``````

**Comment by kddeisz** [comment]
Say is an instance method on the `Thor` class, so you won't be able to use it in the context of the singleton_class. Changing your example to 

```
class Duck < Thor
  def duck
    say 'duck?'
  end
end
```

should fix the problem. i.e. `Duck.new.duck`

**Comment by p8** [comment]
@rafaelfranca I think this issue can be closed.
